#!/usr/bin/env node

const { spawn } = require('child_process');

// Pass arguments
const args = process.argv.slice(2);

// Start backend
const backend = spawn('node', ['backend/src/index.js', ...args], { stdio: 'inherit' });

// Start frontend
const frontend = spawn('node', ['frontend/src/index.js', ...args], { stdio: 'inherit' });